### ISSUE TITLE
is there a way to subscribe an event?

### ISSUE THREAD

**Issue by chrvadala** [moleculerjs/moleculer-repl#12]

**Comment by icebob** [comment]
No, because you can subscribe only from service.

**Comment by chrvadala** [comment]
I see, it should be an interesting feature for debugging.

**Comment by AndreMaz** [comment]
Use `listener add` to subscribe to events
```js
listener add <event.name>
listener add <event.name> --group abcd // with group option
```

`listener remove <event.name>` to unsubscribe and `listener list` to show events that REPL is listening to.
