### ISSUE TITLE
[question] Why stream content in REPL mode passed as string?

### ISSUE THREAD

**Issue by nbvehbq** [moleculerjs/moleculer-repl#30]
https://github.com/moleculerjs/moleculer-repl/blob/4462eaa68a02b2cf7dc536cb29f857e898f39724/src/commands/call.js#L65

In my opinion, when you transfer a file through stream it content must be Buffer not String...
The second parameter may be just a typo?

**Comment by icebob** [comment]
Yes, it's true. Could you send a PR?
