### ISSUE TITLE
None of the commands work

### ISSUE THREAD

**Issue by xeroxstar** [moleculerjs/moleculer-repl#37]
How the commands are working? I tried everything : 
`mol $ nodes -all Invalid Command`
`mol $ nodes -a Invalid Command`
`mol $ nodes[-all] Invalid Command`
`mol $ nodes[-a] Invalid Command`
`mol $ nodes(-a) Invalid Command`
`mol $ nodes(--all) Invalid Command`

> mol $ nmol $ nomol $ nodmol $ nodemol $ nodesmol $ nodes ( <-- not sure if it should be like that ( is what i see in console)
> 
>   Invalid option: '[object Object]'. Showing Help:
> 
>   Usage: nodes [options]
> 
>   List of nodes
> 
>   Options:
> 
>     --help                output usage information
>     -a, --all             list all (offline) nodes
>     -d, --details         detailed list
>     -f, --filter <match>  filter nodes (e.g.: 'node-*')
>     --raw                 print service registry to JSON
>     --save [filename]     save service registry to a JSON file
> 
> mol $

**Comment by AndreMaz** [comment]
All good over here
![cnxWM775qw](https://user-images.githubusercontent.com/9802754/67324390-ac8edd00-f50b-11e9-92df-6e11be50233a.gif)

**Comment by xeroxstar** [comment]
Thanks for the quick reply, see what i get[](https://ibb.co/sydMzqq)

**Comment by AndreMaz** [comment]
Strange. This is what I get when I'm running `nodes --all`

![image](https://user-images.githubusercontent.com/9802754/67325218-b9600080-f50c-11e9-8d3e-24d26691cc74.png)

Are you using `moleculer-runner` to start the services?

**Comment by xeroxstar** [comment]
> Strange. This is what I get when I'm running `nodes --all`
> 
> ![image](https://user-images.githubusercontent.com/9802754/67325218-b9600080-f50c-11e9-8d3e-24d26691cc74.png)
> 
> Are you using `moleculer-runner` to start the services?

No, i am using a basic example  [from this location](https://github.com/moleculerjs/moleculer/blob/master/examples/simple/index.js)

> const broker            = new ServiceBroker({
>         logLevel: "info"
>     });
>     broker.repl()
> broker.createService({... my options});
> broker.start();

Should i start with moleculer-runner to make it work?

**Comment by AndreMaz** [comment]
Hey. No there is no to use `moleculer-runner`. I just tried to narrow down the source of the problem.
Again, the example that you've showed works properly here
![9TRYprmnhw](https://user-images.githubusercontent.com/9802754/67327526-fc6fa300-f50f-11e9-9fc2-ff58b446e8a1.gif)

**Comment by xeroxstar** [comment]
> Hey. No there is no to use `moleculer-runner`. I just tried to narrow down the source of the problem.
> Again, the example that you've showed works properly here
> ![9TRYprmnhw](https://user-images.githubusercontent.com/9802754/67327526-fc6fa300-f50f-11e9-9fc2-ff58b446e8a1.gif)

I see, let me work on it and i will be back with more details... i need to run some tests and debug my application, maybe something wrong on my side.

**Comment by xeroxstar** [comment]
I found the bug and it's on my end, i am using a lodash in the global scope  `global._` (i am running my own mixin with lodash), once i removed it from the global scope, Voilà !!! it's Alive again  ...
