### ISSUE TITLE
Filter match by version

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer-repl#39]
When a project has many services of different versions, then need the ability to filter by version. Now it does not work :(

Examples:
```
services -f v1.**
```

**Comment by icebob** [comment]
`actions -f v1.**`

**Comment by intech** [comment]
@icebob It seemed to me that I tried it too, but now it works :)

**Comment by intech** [comment]
@icebob This does not work with services!

**Comment by icebob** [comment]
Yes, it's true because if checks the service name without version instead of service fullName.

**Comment by intech** [comment]
With actions, a workaround, but not very convenient.

**Comment by icebob** [comment]
Released
