### ISSUE TITLE
Unable to pass meta-data when using --load option

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer-repl#41]
https://github.com/moleculerjs/moleculer-repl/blob/e78ee19f831fdd85fc8e6783534db4e3f80c2cb7/src/commands/call.js#L127

I also tried adding meta to the params file, and looking at the code for the call command, it does not look like meta is supported when loading params from file.

**Comment by icebob** [comment]
I've just released 0.6.4 which supports defining meta keys with `#`.

E.g: 
```
moleculer λ call greeter.echo --load test.json --#user John
```
The `user: "John"` will be placed into the `ctx.meta`.

**Comment by ujwal-setlur** [comment]
What if the ``meta`` object is more complicated than a simple key/value pair? In my services, I pass in an authentication object which is relatively nested in ``meta``. Would love to define it in the ``params`` file. It would be nice if the file could just have this structure:

```js
{
  "params" : {...},
  "meta": {...}
}
```

**Comment by AndreMaz** [comment]
> What if the `meta` object is more complicated than a simple key/value pair? In my services, I pass in an authentication object which is relatively nested in `meta`. Would love to define it in the `json` file. It would be nice if the file could just have this structure:
> 
> ```js
> {
>   "params" : {...},
>   "meta": {...}
> }
> ```

@ujwal-setlur Added in https://github.com/moleculerjs/moleculer-repl/pull/61
