### ISSUE TITLE
Feature request - command history

### ISSUE THREAD

**Issue by icex** [moleculerjs/moleculer-repl#63]
Hi,

We've been using moleculer for some time and we would to have a way to persist the command history (arrow up in repl) after a service restart.

**Comment by AndreMaz** [comment]
Awesome suggestion @icex 👍  https://github.com/moleculerjs/moleculer-repl/pull/64 should add a `.moleculer_repl_history` to homedir. I've tested on Win10 and things seem to be working. Tomorrow will test on Linux.

Can you please install it from the `feature/repl_history` and also do a quick test?

**Comment by icex** [comment]
Works fine on Mac OS(file in homedir ~/.moleculer_repl_history), should be fine on Linux as well..
