### ISSUE TITLE
Unable to set meta when using call

### ISSUE THREAD

**Issue by morkeleb** [moleculerjs/moleculer-repl#69]
When I use the repel with JSON-strings it wont add meta to the call.

```
call v1.myService.action '{"run": true}' '{"myExtra": "data"}'
```

will call the service v1.myService.action with `{run: true}` but it wont add `{myExtra: 'data'}` to the meta of the request. The meta is always only `{ '$repl': true }`.

I start the repl with:
```
  const broker = await startBroker();
  broker.repl()
```

**Comment by AndreMaz** [comment]
Hi @morkeleb 

this should do the trick
```bash
call "math.add" --a 5 --#b Bob --$timeout 1
// params will be { a: 5 }, meta will be { b: 'Bob' } and options will be { timeout: 1 }
```

as an alternative you can use --loadFull flag (more info here: https://github.com/moleculerjs/moleculer-repl/pull/61)

**Comment by morkeleb** [comment]
Yes. But as stated in the documentation the following should work:

```
call [options] <actionName> [jsonParams] [meta]
```

**Comment by icebob** [comment]
@AndreMaz could you reproduce it, plz?

**Comment by AndreMaz** [comment]
@icebob the `#` (e.g,  `--#metaParam` ) option is working fine. However, passing `meta` as JSON encoded as string was failing. 
This PR should fix it https://github.com/moleculerjs/moleculer-repl/pull/71
