### ISSUE TITLE
error: unknown command on REPL

### ISSUE THREAD

**Issue by jellydn** [moleculerjs/moleculer-repl#76]
# What

It's working for me with ver 0.6.6 but got the unknown command with moleculer-repl to v0.7.4. For instance:

```sh
[2023-11-29T02:27:40.129Z] INFO  api-4zb87hdr0pfc6s5k5mox4o/BROKER: ✔ ServiceBroker with 1 service(s) started successfully in 559ms.
mol $ actions
error: unknown command 'actions;'
(Did you mean actions?)
```

## Reproduce steps

Refer https://github.com/jellydn/moleculer-connect/pull/3

Steps:
 - Clone repo
 - Checkout the branch: 'renovate/moleculer-repl-0.x'
 - Run `make`
 [![make](https://i.gyazo.com/d315872f12c254ffe270f1a3441dd6ad.gif)](https://gyazo.com/d315872f12c254ffe270f1a3441dd6ad)
 - Run `make repl`
  [![make repl](https://i.gyazo.com/65256334682d48b85d1344ceb967e3cb.gif)](https://gyazo.com/65256334682d48b85d1344ceb967e3cb)

## Env

```sh
node -v
v20.10.0
```

**Comment by AndreMaz** [comment]
I'm not familiar with the entire setup of your repo but running `npm run build` and then `npm run start` works as expected

![image](https://github.com/moleculerjs/moleculer-repl/assets/9802754/05c590e0-4a3b-4ecb-8bb3-88e6e0bb2c02)

**Comment by jellydn** [comment]
Thanks @AndreMaz I guess you have tested on `main` branch. Could you take a try with `renovate/moleculer-repl-0.x` branch? 

```sh
 - Clone repo
 - Checkout the branch: 'renovate/moleculer-repl-0.x'
```

**Comment by AndreMaz** [comment]
Hi. What I'm trying to say is that, in attempt to isolate the problem, I've skipped the entire logic of your base repo and skipped all the steps that are present in `Makefile`

I copied this repo over here (link to the repo: https://github.com/jellydn/moleculer-typescript-template) that uses moleculer-repl@0.7.4.
![image](https://github.com/moleculerjs/moleculer-repl/assets/9802754/045a0d0c-f63f-499c-a3be-0c9b56318d54)

and then tried to `build` and `start` it. When doing things this way REPL is working as expected.

All of this to say that something at `moleculer-connect` repo is interfering with the REPL

**Comment by jellydn** [comment]
Thanks @AndreMaz for your time.

>I copied this repo over here (link to the repo: [jellydn/moleculer-typescript-template](https://github.com/jellydn/moleculer-typescript-template)) that uses moleculer-repl@0.7.4.

Actually, it's using 2 versions on the moleculer-typescript-template( 0.6.6 and 0.7.4) if you look no the lock file. My point is it's working for `0.6.6` and get weird error with 0.7.4. I closed this issue for now.
